admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9000
dynamic_resources:
  lds_config:
    api_config_source:
      api_type: GRPC
      grpc_services:
        envoy_grpc:
          cluster_name: xds_cluster
node:
  cluster: front-envoy
  id: node1
static_resources:
  clusters:
  - connect_timeout: 1.0s
    health_checks:
    - healthy_threshold: 3
      interval: 5s
      tcp_health_check: {}
      timeout: 1s
      unhealthy_threshold: 3
    hosts:
    - socket_address:
        address: ap-server
        port_value: 30001
    http2_protocol_options: {}
    lb_policy: round_robin
    name: grpc_blue
    type: strict_dns
  - connect_timeout: 1.0s
    health_checks:
    - healthy_threshold: 3
      interval: 5s
      tcp_health_check: {}
      timeout: 1s
      unhealthy_threshold: 3
    hosts:
    - socket_address:
        address: ap-server
        port_value: 30002
    http2_protocol_options: {}
    lb_policy: round_robin
    name: grpc_green
    type: strict_dns
  - connect_timeout: 0.5s
    http2_protocol_options: {}
    lb_policy: round_robin
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: xds-server
                port_value: 30000
    name: xds_cluster
    type: strict_dns
