node:
  cluster: front-envoy
  id: node1
dynamic_resources:
  lds_config:
    api_config_source:
      api_type: GRPC
      grpc_services:
        envoy_grpc:
          cluster_name: xds_cluster
static_resources:
  clusters:
    - &cluster
      name: grpc_blue
      connect_timeout: 1.0s
      type: strict_dns
      lb_policy: round_robin
      http2_protocol_options: {}
      health_checks:
        - timeout: 1s
          interval: 5s
          unhealthy_threshold: 3
          healthy_threshold: 3
          tcp_health_check: {}
      hosts:
        - socket_address:
            address: ap-server
            port_value: 30001
    - <<: *cluster
      name: grpc_green
      hosts:
        - socket_address:
            address: ap-server
            port_value: 30002
    - name: xds_cluster
      connect_timeout: 0.5s
      type: strict_dns
      lb_policy: round_robin
      http2_protocol_options: {}
      load_assignment:
        cluster_name: xds_cluster
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address: {address: xds-server, port_value: 30000}
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9000